name: release-tag

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+"]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Extract and Store Trimmed Repository Name
        run: |
          REPO_CHART_NAME="${{ github.repository }}"
          REPO_APP_NAME=$(echo "$REPO_CHART_NAME" | sed 's/-chart$//')  # Remove "-chart" suffix if present
          
          # Check if the trimmed repo exists
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$REPO_APP_NAME")

          if [[ "$HTTP_STATUS" -eq 200 ]]; then
            echo "Using trimmed repository name: $REPO_APP_NAME"
            echo "REPO_APP_NAME=$REPO_APP_NAME" >> $GITHUB_ENV
          else
            echo "Trimmed repository not found. Falling back to original repository name."
            echo "REPO_APP_NAME=$REPO_CHART_NAME" >> $GITHUB_ENV
          fi

      - name: Use the Stored Variable
        run: |
          echo "Trimmed Repository Name: ${{ env.REPO_APP_NAME }}"

      - name: Set GitHub Token
        id: authenticate
        run: |
          echo "token=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT

      - name: Extract latest App Version
        id: chart_version
        run: |
          # Get the current tag that triggered this workflow
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          echo "tag=$CURRENT_TAG" >> $GITHUB_OUTPUT
          echo "Chart version (from tag): $CURRENT_TAG"

      - name: Extract latest Chart Version
        id: app_version
        run: |
          # For tag releases, use the same version as the tag
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          echo "tag=$CURRENT_TAG" >> $GITHUB_OUTPUT
          echo "App version (from tag): $CURRENT_TAG"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Print Version
        run: |
          echo APP_VERSION:${{steps.app_version.outputs.tag}}
          echo CHART_VERSION:${{steps.chart_version.outputs.tag}}

      - name: Update Chart.yaml versions
        run: |
          # Update chart version
          sed -i "s/version: .*/version: ${{ steps.chart_version.outputs.tag }}/g" ./chart/Chart.yaml
          # Update app version  
          sed -i "s/appVersion: .*/appVersion: \"${{ steps.app_version.outputs.tag }}\"/g" ./chart/Chart.yaml
          echo "Updated Chart.yaml:"
          cat ./chart/Chart.yaml

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ steps.authenticate.outputs.token }}
          charts_dir: ./
          charts_url: https://charts.krateo.io
          owner: krateoplatformops
          repository: helm-charts
          branch: gh-pages
